"""add_categoria_fk

Revision ID: a9744362be42
Revises: 8b28f25c837c
Create Date: 2025-10-20 20:21:18.819913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9744362be42'
down_revision: Union[str, Sequence[str], None] = '8b28f25c837c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.drop_column('atletas', 'categoria_id')
    # ### end Alembic commands ###
